version: "3.9"
name: amen-schedule
services:
  nginx:
    image: "koalayt/amen-schedule-nginx:20221231-132217-415a1fc"
    networks:
      - amen-schedule
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - server
    restart: always

  server:
    image: "koalayt/amen-schedule-api:20221231-132215-415a1fc"
    networks:
      - amen-schedule
    depends_on:
      - postgres
    restart: always

  postgres:
    image: "postgres:15.1"
    networks:
      - amen-schedule
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=amen
      - POSTGRES_PASSWORD=amen
      - POSTGRES_DB=amen_schedule
    restart: always

networks:
  amen-schedule:
volumes:
  postgres-data:
