version: "3.9"
name: amen-schedule
services:
  nginx:
    image: "koalayt/amen-schedule-nginx:1.0.3"
    networks:
      - amen-schedule
    ports:
      - 80:80
    depends_on:
      - server
    restart: always

  server:
    image: "koalayt/amen-schedule-api:1.1.2"
    networks:
      - amen-schedule
    depends_on:
      - postgres
    restart: always

  postgres:
    image: "postgres:15.1"
    networks:
      - amen-schedule
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=amen
      - POSTGRES_PASSWORD=amen
      - POSTGRES_DB=amen_schedule
    restart: always

networks:
  amen-schedule:
volumes:
  postgres-data:
