version: "3.9"
name: amen-schedule
services:
  server:
    build: .
    networks:
      - amen-schedule
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: npm run dev

  postgres:
    image: "postgres:15.1"
    networks:
      - amen-schedule
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=amen
      - POSTGRES_PASSWORD=amen
      - POSTGRES_DB=amen_schedule

networks:
  amen-schedule:
volumes:
  postgres-data:
