version: "3.9"

services:
  postgres:
    image: "postgres:15.1"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=test
