name: server build CI

on:
  workflow_run:
    workflows: ["server test CI"]
    branches: [ master ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      forceBuild:
        description: 'force build images'
        required: false
        type: boolean
        default: false

jobs:
  build-server:
    if: ${{ inputs.forceBuild || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/amen-schedule-api:latest
          context: "{{ defaultContext }}:server"
  build-nginx:
    if: ${{ inputs.forceBuild || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/amen-schedule-nginx:latest
          context: "{{ defaultContext }}:server/nginx"

