// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AmsDay: typeof import('./src/components/AmsDay.vue')['default']
    AmsEditLesson: typeof import('./src/components/AmsEditLesson.vue')['default']
    AmsLoading: typeof import('./src/components/AmsLoading.vue')['default']
    AmsOptions: typeof import('./src/components/AmsOptions.vue')['default']
    AmsTimeline: typeof import('./src/components/AmsTimeline.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanPopup: typeof import('vant/es')['Popup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
