// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AmsDay: typeof import('./src/components/AmsDay.vue')['default']
    AmsEditLesson: typeof import('./src/components/AmsEditLesson.vue')['default']
    AmsEditStatDate: typeof import('./src/components/AmsEditStatDate.vue')['default']
    AmsEditStudent: typeof import('./src/components/AmsEditStudent.vue')['default']
    AmsStudent: typeof import('./src/components/AmsStudent.vue')['default']
    AmsTimeline: typeof import('./src/components/AmsTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanShareSheet: typeof import('vant/es')['ShareSheet']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
